import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/icons";
import { CatalogueGallery } from "@/components/catalogue-gallery";
import { BusinessStory } from "@/components/business-story";
import { ShopMap } from "@/components/shop-map";
import { VisitBanner } from "@/components/shell";
import { featuredDesigns, designs, byBrand, designAlt } from "@/lib/catalogue";
import { site, brands, faqs, browsingSteps } from "@/lib/site";
import { HomeSchemas, pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("/");
export default function HomePage() {
  const features = featuredDesigns();
  const hero = designs.find(d => d.id === "kmi-p013-01");
  const heroSecond = designs.find(d => d.id === "kmi-p015-01");
  return <><section className="hero"><div className="container hero-layout"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"/> A WORLD OF TEXTURES & POSSIBILITIES</p><h1>Every great space<br/>starts with<br/><em>the right surface.</em></h1><p className="hero-description">Explore plywood designs for your next project.<br/>Discover ZRK, KMI and MECATA at Master Plywood.</p><div className="hero-actions"><Link href="/catalogue" className="button button-dark">Explore catalogue <Icon name="arrow"/></Link><Link className="text-link" href="/contact">Find our shop <Icon name="external"/></Link></div><div className="hero-footnote"><span className="little-star" aria-hidden="true">✳</span><span>Browse online. Get inspired.<br/>See your ideas come to life in person.</span></div></div><div className="hero-art"><div className="hero-art-label"><span>THE MATERIAL EDIT</span><span>01 — WOOD & TEXTURE</span></div><div className="material-composition"><div className="material-back" aria-hidden="true">{heroSecond && <Image src={heroSecond.fullImage} alt="" width={heroSecond.width} height={heroSecond.height} priority sizes="(max-width: 800px) 35vw, 24vw"/>}</div><div className="material-main">{hero && <Image src={hero.fullImage} alt={designAlt(hero)} width={hero.width} height={hero.height} priority sizes="(max-width: 800px) 58vw, 34vw"/>}<span className="material-note">A closer look at natural detail<span>KMI CATALOGUE COLLECTION</span></span></div><div className="material-swatch" aria-hidden="true"><span/><span/><span/></div><span className="hero-art-circle" aria-hidden="true">EXPLORE<br/>THE DETAILS <Icon name="arrow"/></span></div><div className="hero-art-bottom"><span>Textures to inspire your next idea.</span><span>MASTER PLYWOOD ↗</span></div></div></div></section>
    <section className="business-intro-band"><div className="container"><p><span className="intro-dot"/>A local business, since August 2020</p><a href={`tel:${site.phone}`}><Icon name="phone"/>{site.phoneDisplay}</a><a href={site.mapsUrl} target="_blank" rel="noopener noreferrer"><Icon name="pin"/>Visit our shop<Icon name="external"/></a></div></section>
    <section className="container article-finder" aria-labelledby="article-finder-title"><div><p className="eyebrow">HAVE A DESIGN IN MIND?</p><h2 id="article-finder-title">Find it by <em>article code.</em></h2><p>Enter a code from your catalogue, or explore by design and brand.</p></div><form action="/catalogue" role="search"><label className="sr-only" htmlFor="home-article-code">Search by article code or design name</label><div><Icon name="search"/><input id="home-article-code" name="q" type="search" placeholder="Try 5077, 7001 or M-03" required autoComplete="off"/></div><button className="button button-dark" type="submit">Find design<Icon name="arrow"/></button></form></section>
    <section className="brand-band" aria-label="Brands in our catalogue"><div className="container"><p>THREE BRANDS.<br/>ENDLESS INSPIRATION.</p><div>{brands.map(b => <Link key={b.slug} href={`/catalogue/${b.slug}`} className={`brand-word brand-${b.slug}`}>{b.name}<Icon name="arrow"/></Link>)}</div><span>Explore the collections <Icon name="arrow"/></span></div></section>
    <section className="section container" id="brands"><div className="section-heading"><div><p className="eyebrow">THE COLLECTIONS</p><h2>Three ways to find<br/><em>your kind of surface.</em></h2></div><p>From quiet wood grains to expressive patterns,<br className="desktop-break"/> explore each brand’s catalogue at your own pace.</p></div><div className="brand-grid">{brands.map((b,i) => {
      const design = designs.find(d => d.id === ["zrk-p013-02", "kmi-p014-01", "mecata-p002-03"][i]);
      return <Link key={b.slug} href={`/catalogue/${b.slug}`} className="brand-card"><div className="brand-card-image">{design && <Image src={design.thumbnail} alt={designAlt(design)} width={design.width} height={design.height} sizes="(max-width: 700px) 90vw, 33vw"/>}<span className="brand-number">0{i+1}</span><span className="brand-card-word">{b.name}</span></div><div className="brand-card-caption"><div><h3>{b.name} collection</h3><p>{byBrand(b.slug).length} designs to explore</p></div><span className="circle-arrow"><Icon name="arrow"/></span></div></Link>;
    })}</div></section>
    <section className="featured-section"><div className="container section"><div className="section-heading"><div><p className="eyebrow">A LITTLE INSPIRATION</p><h2>Details worth<br/><em>a closer look.</em></h2></div><Link href="/catalogue" className="text-link">View all designs <Icon name="arrow"/></Link></div><CatalogueGallery designs={features} featured/></div></section>
    <BusinessStory/>
    <div className="container home-map"><ShopMap/></div>
    <section className="how-section"><div className="container section"><div className="section-heading"><div><p className="eyebrow">FROM AN IDEA TO A CONVERSATION</p><h2>Make a little room<br/><em>for inspiration.</em></h2></div><p>How to explore designs at Master Plywood.</p></div><ol className="steps-grid">{browsingSteps.map((step,i) => <li key={step.name}><span className="step-number">0{i+1}</span><h3>{step.name}</h3><p>{step.text}</p></li>)}</ol></div></section>
    <section className="section container faq-section"><div><p className="eyebrow">A FEW THINGS TO KNOW</p><h2>Before you<br/><em>start exploring.</em></h2></div><div className="faq-list">{faqs.map(faq => <details key={faq.question}><summary><h3>{faq.question}</h3><Icon name="plus"/></summary><p>{faq.answer}</p></details>)}</div></section><VisitBanner/><HomeSchemas/></>;
}
